In [1]:
import pandas as pd

df = pd.read_csv('../raw_data/laps.csv')

df['LocationYear'] = df['Location'] + ' ' + df['Year'].astype(str)

wet_gp = df[(df['Compound'] == 'INTERMEDIATE') | (df['Compound'] == 'WET')]['LocationYear'].unique()

rainy_gp = df['LocationYear'].isin(wet_gp)
df = df[~rainy_gp]
df

/var/folders/6b/wyfstlmd3c54c_2bb3_wfjh40000gn/T/ipykernel_77445/387695507.py:3: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../raw_data/laps.csv')

,Unnamed: 0,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,...,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Location,Year,LocationYear
0,0,0 days 00:08:53.241000,GAS,10,0 days 00:01:45.060000,1.0,NaN,0 days 00:00:04.103000,NaN,NaN,...,NaN,1.0,17.0,False,NaN,False,False,Melbourne,2018,Melbourne 2018
1,1,0 days 00:10:26.613000,GAS,10,0 days 00:01:33.372000,2.0,1.0,NaN,NaN,0 days 00:00:31.357000,...,NaN,1.0,17.0,False,NaN,False,True,Melbourne,2018,Melbourne 2018
2,2,0 days 00:11:59.474000,GAS,10,0 days 00:01:32.861000,3.0,1.0,NaN,NaN,0 days 00:00:31.160000,...,NaN,1.0,17.0,False,NaN,False,True,Melbourne,2018,Melbourne 2018
3,3,0 days 00:13:31.658000,GAS,10,0 days 00:01:32.184000,4.0,1.0,NaN,NaN,0 days 00:00:30.835000,...,NaN,1.0,17.0,False,NaN,False,True,Melbourne,2018,Melbourne 2018
4,4,0 days 00:15:03.990000,GAS,10,0 days 00:01:32.332000,5.0,1.0,NaN,NaN,0 days 00:00:30.716000,...,NaN,2.0,17.0,False,NaN,False,True,Melbourne,2018,Melbourne 2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125754,125754,0 days 02:25:43.046000,SAR,2,0 days 00:01:21.280000,61.0,3.0,NaN,NaN,0 days 00:00:24.354000,...,2023-06-04 14:25:21.773,1.0,20.0,False,NaN,False,True,Barcelona,2023,Barcelona 2023
125755,125755,0 days 02:27:05.180000,SAR,2,0 days 00:01:22.134000,62.0,3.0,NaN,NaN,0 days 00:00:23.675000,...,2023-06-04 14:26:43.053,1.0,20.0,False,NaN,False,True,Barcelona,2023,Barcelona 2023
125756,125756,0 days 02:28:25.600000,SAR,2,0 days 00:01:20.420000,63.0,3.0,NaN,NaN,0 days 00:00:23.634000,...,2023-06-04 14:28:05.187,1.0,20.0,False,NaN,False,True,Barcelona,2023,Barcelona 2023
125757,125757,0 days 02:29:45.580000,SAR,2,0 days 00:01:19.980000,64.0,3.0,NaN,NaN,0 days 00:00:23.602000,...,2023-06-04 14:29:25.607,1.0,20.0,False,NaN,False,True,Barcelona,2023,Barcelona 2023
125758,125758,0 days 02:31:05.834000,SAR,2,0 days 00:01:20.254000,65.0,3.0,NaN,NaN,0 days 00:00:23.633000,...,2023-06-04 14:30:45.587,1.0,20.0,False,NaN,False,True,Barcelona,2023,Barcelona 2023

In [2]:
df.columns

Index(['Unnamed: 0', 'Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber',
       'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time',
       'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime',
       'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST',
       'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team',
       'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted',
       'DeletedReason', 'FastF1Generated', 'IsAccurate', 'Location', 'Year',
       'LocationYear'],
      dtype='object')